version: '2'
services:
  jenkins:
    image: jenkins-with-the-lot
    build: .
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - ~/.aws/jenkins_credentials:/var/jenkins_home/.aws/credentials
      - ./jenkins_home:/var/jenkins_home